### ISSUE TITLE
needs update

### ISSUE THREAD

**Issue by rufftruffles** [parthpower/CloudFlare-DDNS-Client#2]
you need to add the identifier in the request as well otherwise it keeps adding the subdomain over and over into cloudflare.

**Comment by parthpower** [comment]
According to [CloudDns API](https://api.cloudflare.com/#dns-records-for-a-zone-dns-record-details) the request type for record update is `PUT`.  That's implemented at https://github.com/parthpower/CloudFlare-DDNS-Client/blob/dd311214d62639e0108967559a87bcd44f0c5dc9/cf_ddns.sh#L141-L149

Let me know if this is what you were talking about.

**Comment by parthpower** [comment]
Just realized what you were talking about. https://github.com/parthpower/CloudFlare-DDNS-Client/blob/dd311214d62639e0108967559a87bcd44f0c5dc9/cf_ddns.sh#L147

Should be 
```bash
content=$(curl -s -X PUT $headers $endpoint$id -d "{\"type\":\"A\",\"name\":\"$a_name\",\"content\":\"$ip\",\"proxied\":false}"); 
```

Will fix and test. Thanks.

**Comment by rufftruffles** [comment]
DNS_ZONE=Xxxxxxxxx
IDENTIFIER=xxxxxxxxx
AUTH_EMAIL=xxxxxxxx
AUTH_KEY=xxxxxx

curl "https://api.cloudflare.com/client/v4/zones/$DNS_ZONE/dns_records/$IDENTIFIER" \
     --silent \
     -X PUT \
     -H "Content-Type: application/json" \
     -H "X-Auth-Email: $AUTH_EMAIL" \
     -H "X-Auth-Key: $AUTH_KEY" \
     -d "$_UPDATE"

That's what you need to use

**Comment by parthpower** [comment]
`$endpoint` is `https://api.cloudflare.com/client/v4/zones/$DNS_ZONE/dns_records` already so I just changed it `$endpoint/$id` for the record update.
